name: console
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'


dependencies:
  dsqlite:
    path: ../../dsqlite

dev_dependencies:
  lints: ^1.0.0
