name: database_orm_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  build: ^2.1.0
  analyzer: ^2.2.0
  source_gen: ^1.1.0
  code_builder: ^4.1.0

  database_sql: ^0.0.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_test: ^2.1.3
