name: console
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'


dependencies:
  database_sql: ^0.0.2
dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.2
  database_orm_generator:
    path: ../../../database_orm_generator